FROM apache/airflow:2.7.3-python3.10

USER root

# Install system dependencies
RUN apt-get update -qq && apt-get install -y --no-install-recommends \
    curl \
    && rm -rf /var/lib/apt/lists/*

USER airflow

# Install Python dependencies
RUN pip install --no-cache-dir -q \
    scikit-learn \
    xgboost \
    pandas \
    psycopg2-binary \
    apache-airflow-providers-apache-spark

